"""Alert suppression / deduplication (task 16.2).

Implements the suppression half of the Alert System lifecycle (design "Alert
System", Requirement 13.3): *for any* two alert conditions for the same
workload occurring within a **15-minute window**, the second is suppressed
rather than delivered as a brand-new alert, and the existing alert's
``suppression_count`` is incremented.

The alert generated by :mod:`backend.modules.alerts.alert_engine` is derived
from a workload's Priority Score (the platform raises one consolidated alert
per workload condition rather than per raw issue), so deduplication is keyed on
``workload_id`` against the workload's most recent still-open alert
(:func:`backend.services.alert_service.get_active_alert`, where "open" means
``active`` or ``delivery_failed``).

Flow used by the generation path:

#. A new alert-worthy score arrives for a workload.
#. :func:`check_and_suppress` looks up the workload's active alert.
#. If one exists and was created within :data:`SUPPRESSION_WINDOW`, the new
   alert is **suppressed**: the existing alert's ``suppression_count`` is
   incremented and its ``suppressed_until`` extended to ``now + window``; the
   updated existing alert dict is returned (signal to the caller: do not create
   or fire a new alert).
#. Otherwise :func:`check_and_suppress` returns ``None`` and generation
   proceeds normally.

This module only reads/updates persisted alerts; it never emits events.
"""

from __future__ import annotations

import logging
from datetime import datetime, timedelta, timezone

from backend.schemas.alert import Alert
from backend.services import alert_service

logger = logging.getLogger("clover.alerts.suppression")

# Duplicate-suppression window for the same workload (design "Alert System").
SUPPRESSION_WINDOW = timedelta(minutes=15)


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


def _parse_dt(value) -> datetime | None:
    """Coerce a stored timestamp (ISO string or datetime) to aware datetime."""
    if value is None:
        return None
    if isinstance(value, datetime):
        dt = value
    else:
        try:
            dt = datetime.fromisoformat(str(value))
        except ValueError:
            return None
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    return dt


def is_within_window(
    existing: dict, *, now: datetime | None = None
) -> bool:
    """Return True if ``existing`` falls inside the active suppression window.

    The window is anchored on the alert's ``created_at`` and lasts
    :data:`SUPPRESSION_WINDOW`. A previously-set ``suppressed_until`` in the
    future also keeps the window open (so repeated duplicates keep extending
    suppression rather than escaping it).
    """
    now = now or _utcnow()
    created_at = _parse_dt(existing.get("created_at"))
    if created_at is not None and now - created_at <= SUPPRESSION_WINDOW:
        return True
    suppressed_until = _parse_dt(existing.get("suppressed_until"))
    return suppressed_until is not None and suppressed_until >= now


def apply_suppression(
    existing: dict, *, now: datetime | None = None, db_path: str | None = None
) -> Alert:
    """Record a suppressed duplicate against an existing alert.

    Increments ``suppression_count`` and extends ``suppressed_until`` to
    ``now + SUPPRESSION_WINDOW``, persisting the updated alert in place.
    Returns the updated :class:`Alert`.
    """
    now = now or _utcnow()
    alert = Alert.model_validate(existing)
    alert.suppression_count = (alert.suppression_count or 0) + 1
    alert.suppressed_until = now + SUPPRESSION_WINDOW
    alert_service.update_alert(alert, db_path=db_path)
    logger.info(
        "Suppressed duplicate alert for workload %s (alert %s, count=%d)",
        alert.workload_id,
        alert.alert_id,
        alert.suppression_count,
    )
    return alert


def check_and_suppress(
    workload_id: str, *, now: datetime | None = None, db_path: str | None = None
) -> dict | None:
    """Suppress a new alert for ``workload_id`` if a recent one is still open.

    Returns the updated existing alert (as a dict) when the new condition was
    suppressed — the caller MUST then skip creating / firing a new alert.
    Returns ``None`` when there is no active alert in the window and generation
    should proceed.
    """
    existing = alert_service.get_active_alert(workload_id, db_path=db_path)
    if existing is None:
        return None
    if not is_within_window(existing, now=now):
        return None
    return apply_suppression(existing, now=now, db_path=db_path).model_dump(
        mode="json"
    )
