"""Property-based tests for detection output (task 3.6).

Exercises three correctness properties of the Module 1 detection pipeline
(`backend/modules/detection_insight/detector.py`) using Hypothesis. Telemetry is
generated by varying values *around the detection-rule thresholds* (see
`backend/rules/detection_rules.json`) and pairing each payload with a workload
context whose environment / construction_workflow satisfies the targeted rule,
so every generated example is guaranteed to make at least one detection rule
fire and therefore produce an Issue.

**Property 2: Detection Output Structure Invariant**
    For any telemetry that produces an Issue, the Issue carries a non-null
    ``ml_result`` (numeric anomaly_score + boolean is_anomaly), an
    ``xai_explanation`` with >= 3 ``top_contributing_factors`` each referencing
    a feature from the input feature set, and a non-empty
    ``llm_user_explanation``.

**Property 3: Issue Classification Invariant**
    For any produced Issue, ``issue_type`` is one of the 7 defined types,
    ``severity`` is one of {low, medium, high, critical}, and
    ``confidence_score`` is in [0.0, 1.0].

**Property 4: Issue Consolidation**
    For multiple detections on the same workload within the 5-minute window, the
    detector consolidates to a single Issue whose severity equals the maximum of
    the contributing detections' severities (no duplicate issues).

**Validates: Requirements 2.1, 2.2, 3.1, 3.2, 3.3, 4.1, 4.2**

An isolated temp SQLite DB is configured via ``CLOVER_DB_PATH`` before the app /
config is imported so these tests never touch the real ``clover.db``. The
detector's DB-backed helpers are exercised directly via the ``db_path``
argument.
"""

from __future__ import annotations

import os
import shutil
import tempfile
from datetime import datetime, timezone

import pytest
from hypothesis import HealthCheck, given, settings
from hypothesis import strategies as st

# --- Configure an isolated temp DB BEFORE importing the app/config -----------
_TMP_DIR = tempfile.mkdtemp(prefix="clover_detection_prop_")
_TMP_DB = os.path.join(_TMP_DIR, "test_clover.db")
os.environ["CLOVER_DB_PATH"] = _TMP_DB

from backend.core.config import get_settings  # noqa: E402

get_settings.cache_clear()  # ensure the temp DB path is picked up

import json  # noqa: E402

from backend.core.database import connection, init_db  # noqa: E402
from backend.modules.detection_insight import detector  # noqa: E402
from backend.modules.detection_insight.isolation_forest import (  # noqa: E402
    FEATURE_COLUMNS,
)
from backend.schemas.telemetry import TelemetrySnapshot  # noqa: E402
from backend.schemas.workload import Workload  # noqa: E402
from backend.services import issue_service  # noqa: E402

# --------------------------------------------------------------------------- #
# Domain constants under test
# --------------------------------------------------------------------------- #
DEFINED_ISSUE_TYPES = {
    "public_storage",
    "critical_exposed_vulnerability",
    "idle_or_overprovisioned_workload",
    "carbon_heavy_workload",
    "no_monitoring",
    "high_error_rate",
    "cost_spike_or_waste",
}
SEVERITIES = {"low", "medium", "high", "critical"}
_FEATURE_SET = set(FEATURE_COLUMNS)
_COST_MAX = 999999.99


# --------------------------------------------------------------------------- #
# Test workload contexts (seeded once into the temp DB for the FK constraint)
# --------------------------------------------------------------------------- #
_TEST_WORKLOADS: dict[str, Workload] = {
    "prod": Workload(
        workload_id="wl-prop-prod-001",
        workload_name="Prop Prod Web App",
        workload_type="Web App",
        cloud_service_type="container",
        environment="production",
        region="us-east-1",
        owner_team="commerce-team",
        construction_workflow="customer_order_platform",
        workflow_criticality="high",
        status="healthy",
    ),
    "dev": Workload(
        workload_id="wl-prop-dev-001",
        workload_name="Prop Dev BIM",
        workload_type="BIM Job",
        cloud_service_type="vm",
        environment="development",
        region="eu-central-1",
        owner_team="bim-engineering-team",
        construction_workflow="bim_model_data_processing",
        workflow_criticality="medium",
        status="healthy",
    ),
    "staging_batch": Workload(
        workload_id="wl-prop-staging-001",
        workload_name="Prop Staging Reporting",
        workload_type="Batch",
        cloud_service_type="pipeline",
        environment="staging",
        region="us-west-2",
        owner_team="analytics-team",
        construction_workflow="reporting_worker",
        workflow_criticality="medium",
        status="healthy",
    ),
    "testing": Workload(
        workload_id="wl-prop-testing-001",
        workload_name="Prop Testing VM",
        workload_type="VM",
        cloud_service_type="vm",
        environment="testing",
        region="ap-southeast-1",
        owner_team="analytics-team",
        construction_workflow="project_management_dashboard",
        workflow_criticality="low",
        status="healthy",
    ),
}

# Workloads usable for environment-independent scenarios.
_ANY_WORKLOAD_KEYS = list(_TEST_WORKLOADS.keys())
# Non-production workloads (for the idle / over-provisioned rule, DET-COST-001).
_NON_PROD_KEYS = ["dev", "staging_batch", "testing"]
# Workloads on a batch-class construction workflow (for DET-CARBON-001).
_BATCH_KEYS = ["dev", "staging_batch"]


def _seed_workloads() -> None:
    """Insert the test workloads so the issues FK constraint is satisfied."""
    init_db(_TMP_DB)
    with connection(_TMP_DB) as conn:
        for wl in _TEST_WORKLOADS.values():
            conn.execute(
                "INSERT OR IGNORE INTO workloads "
                "(workload_id, workload_name, workload_type, cloud_service_type, "
                " environment, region, owner_team, construction_workflow, "
                " workflow_criticality, status, data) "
                "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
                (
                    wl.workload_id,
                    wl.workload_name,
                    wl.workload_type,
                    wl.cloud_service_type,
                    wl.environment,
                    wl.region,
                    wl.owner_team,
                    wl.construction_workflow,
                    wl.workflow_criticality,
                    wl.status,
                    json.dumps(wl.model_dump(mode="json")),
                ),
            )


_seed_workloads()


def _clear_issues() -> None:
    """Remove all issues so each Hypothesis example starts from a clean slate."""
    with connection(_TMP_DB) as conn:
        conn.execute("DELETE FROM issues")


# --------------------------------------------------------------------------- #
# Telemetry generation: a healthy baseline + per-rule threshold-crossing edits
# --------------------------------------------------------------------------- #
def _healthy_base(workload_id: str) -> dict:
    """A telemetry payload that fires no detection rule on its own."""
    return {
        "workload_id": workload_id,
        "cpu_usage_percent": 45.0,
        "memory_usage_percent": 55.0,
        "storage_gb": 200.0,
        "runtime_hours_24h": 8.0,
        "request_count_24h": 50000,
        "error_rate_percent": 0.4,
        "latency_ms": 120.0,
        "public_exposure": False,
        "public_storage": False,
        "vulnerability_severity": "none",
        "critical_vulnerability_count": 0,
        "access_anomaly_detected": False,
        "monitoring_enabled": True,
        "cost_per_hour": 0.5,
        "cost_24h": 12.0,
        "cost_30d_forecast": 360.0,
        "energy_kwh_24h": 14.0,
        "carbon_kgco2e_24h": 5.6,
        "carbon_intensity_gco2_per_kwh": 400.0,
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }


def _f(lo: float, hi: float):
    return st.floats(min_value=lo, max_value=hi, allow_nan=False, allow_infinity=False)


# Scenario builders: each takes a Hypothesis-drawn override dict and applies it
# to the healthy base for the chosen workload, guaranteeing exactly the targeted
# rule's condition crosses its threshold. Returned key documents the workload
# pool the scenario is compatible with.
def _public_storage(workload_id: str):
    base = _healthy_base(workload_id)
    base["public_storage"] = True
    return st.just(base)


@st.composite
def _critical_vuln(draw, workload_id: str):
    base = _healthy_base(workload_id)
    base["public_exposure"] = True
    base["vulnerability_severity"] = "critical"
    base["critical_vulnerability_count"] = draw(st.integers(min_value=1, max_value=9))
    return base


@st.composite
def _idle(draw, workload_id: str):
    base = _healthy_base(workload_id)
    base["cpu_usage_percent"] = draw(_f(0.0, 9.99))
    base["runtime_hours_24h"] = draw(_f(20.0, 24.0))
    return base


@st.composite
def _carbon_heavy(draw, workload_id: str):
    base = _healthy_base(workload_id)
    base["carbon_kgco2e_24h"] = draw(_f(50.01, 500.0))
    base["energy_kwh_24h"] = draw(_f(80.0, 300.0))
    return base


def _no_monitoring(workload_id: str):
    base = _healthy_base(workload_id)
    base["monitoring_enabled"] = False
    return st.just(base)


@st.composite
def _high_error_rate(draw, workload_id: str):
    base = _healthy_base(workload_id)
    base["error_rate_percent"] = draw(_f(5.01, 100.0))
    return base


@st.composite
def _cost_spike(draw, workload_id: str):
    base = _healthy_base(workload_id)
    base["cost_30d_forecast"] = draw(_f(1000.01, _COST_MAX))
    base["cpu_usage_percent"] = draw(_f(0.0, 29.99))
    return base


@st.composite
def triggering_example(draw):
    """Draw a (Workload, TelemetrySnapshot) pair guaranteed to yield an Issue.

    A scenario is chosen, then a workload whose context satisfies that
    scenario's rule (e.g. the idle rule needs a non-production workload, the
    carbon rule needs a batch-class workflow). Values are varied around the rule
    thresholds so the property is exercised across the whole triggering region.
    """
    scenario = draw(
        st.sampled_from(
            [
                "public_storage",
                "critical_vuln",
                "idle",
                "carbon_heavy",
                "no_monitoring",
                "high_error_rate",
                "cost_spike",
            ]
        )
    )
    if scenario == "idle":
        wl_key = draw(st.sampled_from(_NON_PROD_KEYS))
    elif scenario == "carbon_heavy":
        wl_key = draw(st.sampled_from(_BATCH_KEYS))
    else:
        wl_key = draw(st.sampled_from(_ANY_WORKLOAD_KEYS))

    workload = _TEST_WORKLOADS[wl_key]
    wid = workload.workload_id

    builder = {
        "public_storage": _public_storage,
        "critical_vuln": _critical_vuln,
        "idle": _idle,
        "carbon_heavy": _carbon_heavy,
        "no_monitoring": _no_monitoring,
        "high_error_rate": _high_error_rate,
        "cost_spike": _cost_spike,
    }[scenario]
    payload = draw(builder(wid))
    return workload, TelemetrySnapshot(**payload)


# --------------------------------------------------------------------------- #
# Property 2 - Detection Output Structure Invariant
# --------------------------------------------------------------------------- #
@settings(max_examples=25, deadline=None)
@given(example=triggering_example())
def test_property2_detection_output_structure(example):
    """Any telemetry producing an Issue yields a fully-populated Issue."""
    workload, telemetry = example
    _clear_issues()

    issue = detector.detect(telemetry, workload, db_path=_TMP_DB)

    # The engineered telemetry must trigger a rule and produce an Issue.
    assert issue is not None, "expected an Issue for threshold-crossing telemetry"

    # (a) ml_result: numeric anomaly_score + boolean is_anomaly + model name.
    ml = issue["ml_result"]
    assert ml is not None
    assert isinstance(ml["anomaly_score"], (int, float))
    assert isinstance(ml["is_anomaly"], bool)
    assert isinstance(ml["model_name"], str) and ml["model_name"].strip()

    # (b) xai_explanation: method + >= 3 factors, each referencing an input
    #     feature from the model's feature set.
    xai = issue["xai_explanation"]
    assert xai is not None
    assert isinstance(xai["method"], str) and xai["method"].strip()
    factors = xai["top_contributing_factors"]
    assert len(factors) >= 3
    for factor in factors:
        assert factor["feature"] in _FEATURE_SET
        assert isinstance(factor["impact"], str) and factor["impact"].strip()

    # (c) llm_user_explanation: non-empty string.
    assert isinstance(issue["llm_user_explanation"], str)
    assert issue["llm_user_explanation"].strip()


# --------------------------------------------------------------------------- #
# Property 3 - Issue Classification Invariant
# --------------------------------------------------------------------------- #
@settings(max_examples=25, deadline=None)
@given(example=triggering_example())
def test_property3_issue_classification(example):
    """Any produced Issue has a valid type, severity and confidence."""
    workload, telemetry = example
    _clear_issues()

    issue = detector.detect(telemetry, workload, db_path=_TMP_DB)
    assert issue is not None

    assert issue["issue_type"] in DEFINED_ISSUE_TYPES
    assert issue["severity"] in SEVERITIES
    confidence = issue["confidence_score"]
    assert isinstance(confidence, (int, float))
    assert 0.0 <= confidence <= 1.0


# --------------------------------------------------------------------------- #
# Property 4 - Issue Consolidation (single issue, max severity)
# --------------------------------------------------------------------------- #
# Environment-independent scenarios so any number can be applied to one
# workload within the consolidation window without needing different contexts.
_CONSOLIDATION_BUILDERS = {
    "public_storage": _public_storage,
    "critical_vuln": _critical_vuln,
    "no_monitoring": _no_monitoring,
    "high_error_rate": _high_error_rate,
    "cost_spike": _cost_spike,
}


@st.composite
def consolidation_sequence(draw):
    """Draw a workload + a sequence of 2-4 triggering telemetries for it."""
    wl_key = draw(st.sampled_from(_ANY_WORKLOAD_KEYS))
    workload = _TEST_WORKLOADS[wl_key]
    wid = workload.workload_id
    scenarios = draw(
        st.lists(
            st.sampled_from(sorted(_CONSOLIDATION_BUILDERS.keys())),
            min_size=2,
            max_size=4,
        )
    )
    snapshots = [
        TelemetrySnapshot(**draw(_CONSOLIDATION_BUILDERS[name](wid)))
        for name in scenarios
    ]
    return workload, snapshots


def _standalone_severity(workload: Workload, telemetry: TelemetrySnapshot) -> str:
    """Severity a single telemetry produces in isolation (clean issue table)."""
    _clear_issues()
    issue = detector.detect(telemetry, workload, db_path=_TMP_DB)
    assert issue is not None
    severity = issue["severity"]
    _clear_issues()
    return severity


@settings(
    max_examples=15,
    deadline=None,
    suppress_health_check=[HealthCheck.too_slow],
)
@given(seq=consolidation_sequence())
def test_property4_consolidation_single_issue_max_severity(seq):
    """Same-workload detections within 5 min collapse to one max-severity Issue."""
    workload, snapshots = seq

    # Expected consolidated severity = max severity across the individual
    # detections (each measured in isolation).
    standalone = [_standalone_severity(workload, snap) for snap in snapshots]
    expected_rank = max(issue_service.severity_rank(s) for s in standalone)

    # Now run the full sequence against a single, shared open issue.
    _clear_issues()
    last_issue = None
    for snap in snapshots:
        last_issue = detector.detect(snap, workload, db_path=_TMP_DB)
        assert last_issue is not None

    # Exactly one Issue persisted for the workload (no duplicates).
    persisted = issue_service.list_issues(
        workload_id=workload.workload_id, db_path=_TMP_DB
    )
    assert len(persisted) == 1, f"expected single consolidated issue, got {len(persisted)}"

    # Its severity equals the maximum contributing severity.
    consolidated_severity = persisted[0]["severity"]
    assert issue_service.severity_rank(consolidated_severity) == expected_rank
    assert consolidated_severity in SEVERITIES

    _clear_issues()


def teardown_module(module):  # noqa: D401 - pytest hook
    """Remove the temp DB directory created for this module."""
    shutil.rmtree(_TMP_DIR, ignore_errors=True)
